# Generated by Django 3.2.7 on 2021-10-12 21:15

from django.db import migrations, models
import django.db.models.deletion
import simple_events.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='', upload_to=simple_events.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='simple_events.event'),
        ),
    ]
