# Generated by Django 3.2.7 on 2021-10-12 21:40

from django.db import migrations, models
import simple_events.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_events', '0002_auto_20211012_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='images/placeholder.png', upload_to=simple_events.models.user_directory_path),
        ),
    ]
